<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>LCS</RootNamespace>
    <StartupObject>LCS.Program</StartupObject>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyTitle>2LCS</AssemblyTitle>
    <Company>Microsoft</Company>
    <Product>2LCS</Product>
    <Version>0.42.0</Version>
    <Copyright>Copyright © 2023</Copyright>
    <Description>This utility helps manage D365FO instances deployed in Lifecycle Services projects.</Description>
    <PackageProjectUrl>https://github.com/microsoft/2LCS</PackageProjectUrl>
    <RepositoryUrl>https://github.com/microsoft/2LCS</RepositoryUrl>
    <ApplicationIcon>favicon-white.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Forms/**/*.cs" />
    <Compile Remove="AssetLibrary/AssetLibrarySearch.cs" />
    <Compile Remove="AssetLibrary/AssetLibrarySearch.Designer.cs" />
    <Compile Remove="ExtendedWebBrowser.cs" />
    <Compile Remove="NativeMethods.cs" />
    <EmbeddedResource Remove="Forms/**/*.resx" />
    <EmbeddedResource Remove="AssetLibrary/AssetLibrarySearch.resx" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <None Update="LICENSE">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon-blue.ico" />
    <Content Include="favicon-white.ico" />
    <Content Include="Third Party Notices.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="DocX" Version="3.0.23523.1209" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
    <PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.1" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.0" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.0" />
  </ItemGroup>
</Project>
